### ISSUE TITLE
Onboard @akinwale-habibullah Andela Developer

### ISSUE THREAD

**Issue by bdougie** [bdougie/codeNaija#117]
Hi @akinwale-habibullah

The biggest assistance needed is to address the design #91 

1. Please do not push to master, open a Pull Request always. A Netlify preview gets deploy when you do that. 
3. [Project board](https://github.com/bdougie/codeNaija/projects/1) is also useful 
1. Please ask me questions, this site is built with Gatsby but it does not get in the way too much. Infrastructure is explained in the [README](https://github.com/bdougie/codeNaija/blob/master/README.md)
1. If there is a bug. [Open an issue](https://github.com/bdougie/codeNaija/issues/new)

**Comment by akinwale-habibullah** [comment]
Hello @bdougie ,

Thanks for the awesome work you've done on this website 👍 👏  and for making out time to meet with me. 

Excited about collaborating with you on this website and also supporting the **codeNaija** Hackaton. 🤝
