### ISSUE TITLE
Website Timer 

### ISSUE THREAD

**Issue by toyae** [bdougie/codeNaija#156]
Hi @akinwale-habibullah 👋 

Can we please add a timer to the website counting down to when we kickoff?
Days, Hours, Minutes, Seconds

**Comment by akinwale-habibullah** [comment]
Hey @toyae,

Sorry for my delayed response. Sure we can. 

For clarity, counting to when? Application closure or event date?

**Comment by toyae** [comment]
Hi @akinwale-habibullah 👋 
Event date please.

**Comment by akinwale-habibullah** [comment]
Hi @toyae 👋.

Please take a look at the landing page, and let me know what you think?

Do we need to make further changes to it?

**Comment by toyae** [comment]
looks good 👍 

thank you
