### ISSUE TITLE
Add Better FAQ css

### ISSUE THREAD

**Issue by bdougie** [bdougie/codeNaija#86]
at the moment the style does not match the design 

#91

**Comment by bdougie** [comment]
The first question does not fit:

<img width="1040" alt="Screenshot 2019-10-01 15 34 25" src="https://user-images.githubusercontent.com/5713670/66005679-064a3d00-e461-11e9-894a-737de36885d4.png">

**Comment by akinwale-habibullah** [comment]
Hey @bdougie I fixed this with the last PR I just merged.
